CREATE TABLE person
(
    person_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      varchar(150) NOT NULL UNIQUE,
    birth_year       int CHECK ( person.birth_year < 2010 ) NOT NULL

);

CREATE TABLE book (
                      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title varchar(100) NOT NULL UNIQUE,
                      author varchar(150) NOT NULL,
                      year int CHECK (year > 1700) NOT NULL,
    person_id int REFERENCES person(person_id) ON DELETE SET NULL
);